import os

BOT_TOKEN = os.environ["BOT_TOKEN"] 
DB_PATH = os.environ["DB_PATH"]
PRODUCER_GROUP_ID = os.environ["GROUP_ID"]

ROLE_UNAUTHENTICATED = "UNAUTHENTICATED"
ROLE_CLIENT = "CLIENT"
ROLE_PRODUCER = "PRODUCER"

